#17: Add 'copy' button for each key and value in the key-values view
syrotenko/vault-desc-ui pull request #28
Opened 2022-08-24 18:49 UTC by olena-syrotenko

Implemented copying as an event, it will work if we click on the key-value row, so the "copy" icon is not needed as a functionality, but can be added as a functionality description element. Also, changed filling of the table depending on the selected folder.

2022-08-24 18:59 UTC, syrotenko requested changes

2022-08-24 18:59 UTC, syrotenko commented on app_view.py
> +        data = self.viewmodel.get_node_data(node_path)
Do we really need to get data using vault?
Selected node already should contain key-values. Probably, it's better just to get currently selected node and fetch `kv` from it

2022-08-24 18:59 UTC, syrotenko commented on app_view.py
> +        values = self.vault_data.item(item, 'values')
It's better to implement separate coping for both key and value. If TKinter doesn't allow implement it in the fast way, leave the current implementation

2022-08-24 19:15 UTC, olena-syrotenko commented on app_view.py
> +        values = self.vault_data.item(item, 'values')
`Values` is a tuple that contains both key and value, so we are able to get them using the index. If nedded, I will add separate variables for key and value

2022-08-24 19:21 UTC, olena-syrotenko commented on app_view.py
> +        data = self.viewmodel.get_node_data(node_path)
Maybe this way will be better if we store this information in node finally. But when we each time access to vault it ensures that data are up to date

2022-08-29 14:03 UTC, syrotenko approved these changes

2022-08-31 09:56 UTC, merged