#2: Use command line argumnets instead of constants in the json-data-to-vault-commands.py
syrotenko/vault-desc-ui pull request #8
Opened 2022-08-17 07:52 UTC by olena-syrotenko

2022-08-17 08:02 UTC, olena-syrotenko commented
Need I make another parameters such as VENV-PATH, SCRIPT-PATH etc in populate_vault.ps1 as a command line arguments?

2022-08-20 17:39 UTC, syrotenko requested changes

2022-08-20 17:39 UTC, syrotenko commented on populate-vault.ps1
> +    [string]$d
I think it's better to get data from the variable instead of arguments in this case

2022-08-21 08:15 UTC, syrotenko approved these changes

2022-08-21 08:23 UTC, merged