#3: vault is incorrectly populated with secrets from the data file
syrotenko/vault-desc-ui pull request #9
Opened 2022-08-17 10:07 UTC by olena-syrotenko

2022-08-18 13:51 UTC, syrotenko requested changes

2022-08-18 13:51 UTC, syrotenko commented on json-data-to-vault-commands.py
> +            print(f'{current_path}/{k}')
PowerShell script (`populate-vault.ps1`) uses output of this script as `vault` commands.
This "print" is used as command and the error appears:
```powershell
secret/d3/d33
secret/d3/d33 : The term 'secret/d3/d33' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that 
the path is correct and try again.
```
Please, avoid any output except `vault` commands or suggest another way how to convert json data to the `vault` commands.
Probably, we can write `vault` commands to the temporary file. Pass the path to the tmp file to the `json-data-to-vault-commands.py` script and after execution just read this file and perform commands from it. It will allow us to not care about output of `json-data-to-vault-commands.py` script

2022-08-18 13:51 UTC, syrotenko commented on json-data-to-vault-commands.py
> +    return f'vault kv patch {path} {key}={val}'
Error appears when we use `patch` command if "directory" doesn't yet exist:
```powershell
> vault kv patch secret/d3/d33 privat=privat_pass
Error writing data to secret/data/d3/d33: Error making API request.
```

There is no way to check if "directory" exists in this script. Probably, this script should return just path and key=value:
```powershell
secret/d3/d33 privat=privat_pass
```
and `populate-vault.ps1` will decide what command to use, `put` or `patch`.
For example, firstly we can try to `patch` record and after that check the last return code:
```powershell
> vault kv patch secret/d3/d34 spotify=spotify_pass
> $LASTEXITCODE
2
```
If the last return code != 0 we use `put` command.

2022-08-18 14:06 UTC, syrotenko commented on json-data-to-vault-commands.py
> +            print(f'{current_path}/{k}')
I created separate issue for "output problem": #10

2022-08-19 08:23 UTC, olena-syrotenko commented on json-data-to-vault-commands.py
> +    return f'vault kv patch {path} {key}={val}'
done

2022-08-19 08:27 UTC, olena-syrotenko commented on json-data-to-vault-commands.py
> +            print(f'{current_path}/{k}')
I forgot to delete this string that has been added only for my test. It doesn't matter for the script work. I will fix it in the #10 issue

2022-08-19 08:54 UTC, olena-syrotenko commented on json-data-to-vault-commands.py
> +            print(f'{current_path}/{k}')
Okay, I can't make these changes in another issue, because they are only on this branch, so i am fixing it here

2022-08-20 17:59 UTC, syrotenko approved these changes

2022-08-20 18:08 UTC, merged